name: Python CI/CD

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-test:
    runs-on: [linux, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest

      - name: Test with pytest
        run: |
          pytest tests

      - name: Test with mypy
        run: |
          mypy src/
          
      - name: Test with black
        run: |
          black --diff --check src/

      - name: Test with isort
        run: |
          isort --check-only -- diff --profile black src/
          
      - name: Test with flake8
        run: |
          flake8 src/
      
